language: ruby
sudo: false
git:
  depth: 1
cache: bundler
script:
  - bundle exec jekyll build
after_success:
  - git fetch --depth 1 origin refs/heads/master:refs/remotes/origin/master
  - git branch -a
  - git checkout -b master origin/master
  - mv CNAME .git _site/
  - find . -mindepth 1 -maxdepth 1 -not -name _site -exec rm -r {} \;
  - mv _site/* _site/.git .
  - rmdir _site
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - 'git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git push https://${GH_TOKEN}@github.com/owst/owst.github.io
