language: ruby
sudo: false
git:
  depth: 1
cache: bundler
env:
  secure: MqtmfKeRHHeEenldtvFlx6F7injqm1ZDgkBlAa5dc5PQp0+4RLIKFd5OUj7NIqBROW7Rh0FFQdzVI2RH81IU+7QWoLdFdHCq5DE1UqJ7ps4oRdvMkSPflyA8nTfx/3O9YV1l3o3QQwk9ihSegauIPNzt1n5XvieJERlnG5IuonHs841A7iRFQ1islHeGTwqpREbLH5fglu/WEkWeK6R3JmidbhqT8R2M1/jUpMU+Hfr828fIgWwZCdQuO8yAkkiZcbJeLnNzUMuq9EM3WF2LFj/b4C7LL7kF20gEzapNnl2QSis2Ji0wTqYRCQhYeqcS8S7Lqf4ACtAWfIyQWTcBTkUqBVkVEuEkX2O8Eh98dC2JgnUzOA8A5HxMj/VA3uHBiqK9h817MWybIfLV978qIhBloRTOxbsok1SfOrNwzwAxA6cGymbgiomv+YT0e4cSWmsdsMAuoGFFhraQsrRWXpY1W53QXAP3Pun2xZnQtb98yCMi4IvPfhdzIbWB+7PZNg9r/GXRbijYqq/nT+hihJTYNDmcgrCgi4bJXiv6owZYSMb8NjWa51X1hVSCr442eQ8yKD2cSE2kdepWW2tGxuG8HYrzXhYOAciG+W4G1csd3t9qBplVhtisOMNXQ05tjp9xaHH5WxxpcgJD4sfaT9Ue4CxREr1B9jkD/rkRgyU=
script:
  - bundle exec jekyll build
after_success:
  - git fetch --depth 1 origin refs/heads/master:refs/remotes/origin/master
  - git branch -a
  - git checkout -b master origin/master
  - mv CNAME .git _site/
  - find . -mindepth 1 -maxdepth 1 -not -name _site -exec rm -r {} \;
  - mv _site/* _site/.git .
  - rmdir _site
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - 'git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git push https://${GH_TOKEN}@github.com/owst/owst.github.io
