lang: ruby
env:
  - BRANCH=travis_test_builds
install:
  - bundle install
script:
  - bundle exec jekyll build
after_success:
  - mv CNAME .git _site/
  - find . -mindepth 1 -maxdepth 1 -not -name _site -exec rm -r {} \;
  - mv _site/* .
  - rmdir _site
  - git checkout -b $BRANCH
  - git add .
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git commit --all --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add github
  - git push https://${GH_TOKEN}@github.com/owst/owst.github.io $BRANCH
