exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - blog/generators
  - vendor
name: "Owen Stephens"
email: owen@owenstephens.co.uk
title: "Owen Stephens' Website"
tagline: "London-based Polyglot Programmer"
img_dir: '/assets/images/'
static_dir: '/assets/static/'
timezone: "Europe/London"
kramdown:
  auto_ids: true
  syntax_highlighter: rouge
collections:
    - oss_contributions
defaults:
  -
    scope:
        path: ""
    values:
        global_cloudflare_js_includes:
          # Required by Bootstrap
          - jquery/3.2.1/jquery.min.js
          - popper.js/1.12.9/umd/popper.min.js
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
