exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - blog/generators
  - vendor
name: "Owen Stephens"
email: owen@owenstephens.co.uk
title: "Owen Stephens' Website"
tagline: "Software Engineer"
img_dir: '/assets/images/'
static_dir: '/assets/static/'
timezone: "Europe/London"
kramdown:
  auto_ids: true
  syntax_highlighter: rouge
collections:
    - oss_contributions
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
